# This token will be valid for ~2 hours
import os
import requests
from dotenv import load_dotenv

load_dotenv()


def get_reddit_data(subreddit_name, oauth_token):
    headers = {'User-Agent': 'sentiment-analysis/0.0.1',
               'Authorization': f"bearer {oauth_token}"}
    res = requests.get(f"https://oauth.reddit.com/r/{subreddit_name}/hot",
                       headers=headers)

    res_json = res.json()
    posts = res_json["data"]["children"]
    all_post_texts = []
    # Combine all post titles and bodies into one list
    for post in posts:
        all_post_texts.append(post["data"]["title"] + " " + post["data"]["selftext"])

    return all_post_texts


def get_oauth_token():
    print("getting oauth token")
    reddit_api_id = os.environ.get("REDDIT_API_ID")
    reddit_api_secret = os.environ.get("REDDIT_API_SECRET")
    reddit_username = os.environ.get("REDDIT_USERNAME")
    reddit_password = os.environ.get("REDDIT_PASSWORD")

    # note that CLIENT_ID refers to 'personal use script' and SECRET_TOKEN to 'token'
    auth = requests.auth.HTTPBasicAuth(reddit_api_id, reddit_api_secret)

    # here we pass our login method (password), username, and password
    data = {'grant_type': 'password',
            'username': reddit_username,
            'password': reddit_password}

    # set up our header info, which gives reddit a brief description of our app
    headers = {'User-Agent': 'sentiment-analysis/0.0.1'}

    # send our request for an OAuth token
    res = requests.post('https://www.reddit.com/api/v1/access_token',
                        auth=auth, data=data, headers=headers)

    # convert response to JSON and pull access_token value
    token = res.json()['access_token']

    return token

    # # add authorization to our headers dictionary
    # headers = {**headers, **{'Authorization': f"bearer {token}"}}

    # # while the token is valid (~2 hours) we just add headers=headers to our requests
    # requests.get('https://oauth.reddit.com/api/v1/me', headers=headers)


#
reddit_test_data = [
    # "Sunday Daily Thread: What's everyone working on this week? Tell /r/python what you're working on this week! You can be bragging, grousing, sharing your passion, or explaining your pain. Talk about your current project or your pet project; whatever you want to share.",
    # "Wednesday Daily Thread: Beginner questions New to Python and have questions? Use this thread to ask anything about Python, there are no bad questions!\n\nThis thread may be fairly low volume in replies, if you don't receive a response we recommend looking at r/LearnPython or joining the Python Discord server at [https://discord.gg/python](https://discord.gg/python) where you stand a better chance of receiving a response.",
    # "What are the best Python libraries to learn for beginners? Hi everyone. I wanted to reach out and ask for some help with a Python project I'm working on. So, I'm a CS student and I recently started learning Python and so far, I’m loving it. It's a great language and I even like it better than JavaScript. Anyways, I'm looking forward to continuing to improve my skills in this area.\n\nOne thing I've been struggling with though is all the libraries that come with Python. I'm particularly interested in machine learning, but I'm down to learn any popular libraries that you guys recommend.\n\nI've been doing some research online, but I figured why not ask Reddit. So, if you guys have any good libraries to suggest, that'd be great. Also, if you know of any good places to learn these libraries, I'm all ears.\n\nSo far, I've picked out a few libraries that I found:\n\n* [NumPy](https://numpy.org/): Scientific computing library and I know this one is the most popular especially in Data Science.\n* [DocArray](https://github.com/docarray/docarray): Multimodal Data Library\n* [TensorFlow](https://www.tensorflow.org/) and [PyTorch](https://pytorch.org/): Deep learning library\n* [python-benedict](https://github.com/fabiocaccamo/python-benedict): Dictionary manipulation library\n\nI know we'll be moving on to other languages next semester, but I want to make sure I have a solid understanding of Python as well. I would really appreciate it if you guys could give me some more suggestions. If you have any personal experience with any of these libraries, I would love to hear about it.\n\nNext semester, we'll be moving on to other languages, but I want to make sure I have a solid understanding of Python too. If you have any more libraries to recommend, I'd be grateful.\n\nAlso, if you have any personal experience with any of these libraries or have any project ideas, I'd love to hear about it.\n\nThanks for anyone helping out. Looking forward to diving into these libraries and learning more.",
    # "What does Python uniquely offer for automation? I write JavaScript and when we launched our open source business automation tool, we let users write Node.js code as part of their flows if they can't find an out-of-the-box piece for it.\n\nWe keep hearing from users that they prefer to write Python over JavaScript. We'll add it eventually since it's being consistently requested.\n\nBut.. I'd like to understand from the perspective of Python developers, what is it that Python offers that other languages (namely JavaScript) don't? Any specific features or libraries that you think you'd rely on for automation jobs?\n\nI mean by automation things like: syncing data from service A to service B and so.",
    # "A Music Theory Telegram Bot written in Python This is a Telegram Bot written in Python that helps you to learn Music Theory on the go (audio and visual).\n\n[Music Theory Telegram Bot](https://preview.redd.it/gu0l3xnnsefa1.png?width=960&amp;format=png&amp;auto=webp&amp;v=enabled&amp;s=a8b3e8eda0211d08d4bbe30718b4a6eca73d8b87)\n\nThe application is using python-telegram-bot library\n\nHere you can watch a video on how this application was created: [https://www.youtube.com/watch?v=WCQai649s\\_Q](https://www.youtube.com/watch?v=WCQai649s_Q)\n\nYou can find the full source code on github: [https://github.com/2CoderOK/music-theory-bot](https://github.com/2CoderOK/music-theory-bot)\n\nPlease let me know if you find this application helpful!",
    # "A Beginner's Guide to Mastering AI and Python [First Book on Amazon]  Hey Redditors!\n\nI just wanted to share some exciting news about my latest book, Python and AI: The Ultimate Party Guide for Mastering the Magic of Code! This book is a beginner's guide to AI and Python and is designed to help you master the art of coding with ease.\n\nWith this guide, you'll learn how to incorporate AI into your projects and develop your skills in Python programming. The book covers all the essential concepts, from basic programming to complex AI algorithms, and is packed with interactive examples and hands-on exercises to help you build your knowledge.\n\nAnd the best part? It's designed to be a fun and enjoyable journey, so you'll never get bored along the way! Whether you're a seasoned coder or a complete beginner, this book will help you take your skills to the next level.\n\nIf you're looking to get into AI and Python programming, this book is the perfect starting point. So what are you waiting for? Grab your copy now and start your journey to becoming a coding master!\n\nAnd here's the real kicker: I need your help to make this book #1 on Amazon's Best New Arrival list. If you love Python and AI, and want to help other beginners like yourself, then please buy a copy and leave a positive review. Your support will go a long way in spreading the word and making this book a success.\n\nThank you in advance! Let's make Python and AI: The Ultimate Party Guide for Mastering the Magic of Code the #1 Best New Arrival on Amazon!\n\n$0.99 on [Amazon](https://www.amazon.com/Python-AI-Ultimate-Party-Mastering-ebook/dp/B0BTB4Y1F3)\n\nFREE for Kindle Unlimited",
    # "Making Automatic YouTube Videos with Python Hi everyone! Awhile back I had the idea to fully automate a YouTube channel to see how successful it could become. I'm not new to programming, but I certainly am to Python.\n\nHere's a video I made explaining the process: [https://youtu.be/ZmSb3LZDdf0](https://youtu.be/ZmSb3LZDdf0)\n\nThe way I started was to use those terrible Reddit TikTok/Reel/Shorts where people find a popular post and essentially just read it out with some funny comments. Luckily for me, people already use text-to-speech instead of their own voice, so my solution would fit right in.\n\nTo get content, I first used PRAW to access the Reddit API. I filter through that response and used pyttsv3 to generate an .mp3 of the voiceover. Then Selenium and Firefox made getting screenshots of each comment/post title really easy.\n\nThe only tricky part for me was learning how to use MoviePy to package everything up into a neatly-edited video. I explain this much better in the video above, but it basically consists of creating clip objects with each of the pictures and voiceovers, then connecting them in a CompositeVideoClip.\n\nI'm curious how many others have tried this, as I'm sure the majority of popular stolen Reddit posts can't be all made by hand.\n\nEdit for anyone who wanted source code: [https://github.com/Shifty-The-Dev/RedditVideoGenerator](https://github.com/Shifty-The-Dev/RedditVideoGenerator)",
    # "How to Iterate Over Rows in pandas, and Why You Shouldn't – Real Python ",
    # "Simulator of hypohtetical investment in the past - housing/stock Hi guys :)\n\nI am thinking of a little app, for personal app &amp; with friends or family.\n\nIt would be a simulation of past investment, for example if u investe d 1000€ in Google in 2000, how it would worth in 2020\n\nit could have some features like peak value (when bitcoin was highest for example)\n\nIt would be also good for housing, paris housing was so cheap 30 years ago, it almost double or triple since\n\ni am finishing an ongoig project so i dont start thinking too much about it, i know it could render quiet easy to use on a website - embedding a jupyter notebook\n\nlet me know if u saw something like this, have any tips or comments :) cheers, bye",
    # "Documentation assistant, chat bot that helps with libraries. Fully context aware Im still in the process, but this is the prototype. I will open source soon its just too rough. Think I should spend more time on it as I find it very useful.\n\n[Screenshot 1](https://imgur.com/a/wilpTys)\n\n[Prototype video](https://imgur.com/a/EAWngGo)\n\nBasically its a Chrome extension, that looks at the documentation page and allows users to query it with GPT model with context.\n\nIm requests to scrape data. Than process and prep it for embeddings using Longchain and the openAI's gpt3 as my LLM model. Here I use simple Javascript for frontend and flask backend.\n\nThus the huge advantage is that its context awareness is up to date and not a year or 2 ago like a typical GPT model on its own. You can also use it on private Docs/ repos. Just querying with GPT is good but there are still a lot of incorrect responses if library is frequently updated or not too popular, because it lack context.\n\nIn the end I want to create a nice standalone version which connect with different library indexes + different GPT services/ model\n\nCurrently im thinking to use something like redis queue processing new libraries and some vector DB to store data like Milvus,\n\nI would appreciate any feedback on this, If you find a tool like this useful or not. Also want to see if anyone would be willing to contribute to this project too",
    # "What's the best python projects for freelancing? \n\nI am trying to find some freelancing in python. \n\nIt's looks like is better to focus in web system than bots, automation and scraping.",
    # "Expense Tracker  Hello everyone,\n\nI built an expense tracker long time ago. I looked at the code several weeks ago and realized how bad it was. So I decided to rebuild it and make it better and more important: useful. I will continue working on it and maybe inplementing features like currency coonversion, taxes and more.\n\nI am happy for every feedback I get. For bugs or problems, feel free to create an Issue on GitHub.\n\nRepo: [https://github.com/Jolumine/exptrk](https://github.com/Jolumine/exptrk)",
    # "Transfer the ownership of Flask-Mailing Hi,\nI want to transfer the ownership of the below mentioned project.\n\nFlask-Mailing: Flask mail system for sending mails(individual, bulk) ,attachments(individual, bulk) fully asynchronously..\n\nGitHub: https://github.com/marktennyson/flask-mailing\n\nPYPI: https://pypi.org/project/Flask-Mailing/\n\nDocumentation: https://gh.aniketsarkar.info/flask-mailing/",
    # "Detailed tutorial on How to Use Python and Beautiful Soup for Web Scraping Hello everyone,\nI created a detailed article on how to do web scraping using python and beautiful soup module. This tutorial will cover uses of webscraping, how to install and setup and performing live webscraping on website and how to collect data according to needs. \n\nAs an beginner he can understand all the above mentioned details and learn basics from it and practice it\n\nArticle link [How to Use Python and Beautiful Soup for Web Scraping](https://ideasorblogs.in/learn-how-to-use-python-and-beautiful-soup-for-web-scraping-a-step-by-step-tutorial/)\n\nHope it will be useful for everyone\n\nLet me know in the comment if anything mentioned is wrong",
    # "5 Common Asyncio Errors in Python (and how to avoid them) ",
    # "Using Testing Library with Selenium in Python ",
    # "Cursor clicker program question Hello all,\n\nI want the program to do the following:\n\nuser clicks mouse -&gt; program, preferably in python, clicks too depending on the cursers current location\n\nHow would I go about this? Is there a name for this sort of program?\n\nThank you!",
    # "PyCharm has become horrible to work with over SSH interpreter, any similar experiences? I have been using PyCharm pro for a few years now. I dont remember when exactly but probably last year they reworked the way SSH interpreters are configured?\n\nFor a while now,  I constantly have problems with this stupid config. Maybe I am doing something wrong and it's me who is stupid but it is just so frustrating! It all worked nicely before with some simple settings.\n\n&amp;#x200B;\n\nNow I have problems like:\n\n\\-  confusing coupling of deployment and SSH\n\n\\- deployment not happening where it is supposed to be (see above)\n\n\\- SSH option wizard no longer supports pointing to anaconda directly and somehow changed to be not as intuitive as it used to be\n\n\\- debugging is a feaking hell. PyCharm always wants to jump to some temporary files (which dont have my breakpoints) and it takes me a day to try all kind of settings until it magically works and I have no clue what finally got me to the point...\n\nI have several projects on several servers and this is becoming a huge blocker in my work, being not able to debug properly.\n\n&amp;#x200B;\n\nPlease tell me I am not the only one? ",
    # "I made a ChatGPT clone using Python, but i added voice interaction functionality ! Check the code in description and tell me what do you think ! ",
    # "Django and Flutter. What Flet has joined together. &amp;#x200B;\n\nI hate boilerplate code. I hated it all my life. I made so many steps to remove these mental parasites far from me. And now, with Flet and Django it is possible.  \nAll you need is this package: [https://pypi.org/project/flet-django/](https://pypi.org/project/flet-django/).\n\n* Add 'flet\\_django' to INSTALLED\\_APPS in settings.py: INSTALLED\\_APPS += \\['flet\\_django'\\]\n* Create the main function in the file main\\_app.py at the root of your Django project:  \n\\`\\`\\`python  \nimport flet as ft  \nfrom flet\\_django.pages import GenericApp  \nmain = GenericApp(controls=\\[ft.Text(\"Hello World!\")\\])  \n\\`\\`\\`\n* Run function **main** from file **main\\_app.py** using the Django command:  \n\\`\\`\\`bash  \npython manage.py run\\_app  \n\\`\\`\\`\n* Enjoy your desktop/mobile/web flutter app.",
    # "Understanding Similarity Measures for Text Analysis ",
    # "Python Project Recommendations Hello, me and 3 of my friends have to present a project in python this semester. What topics would you think would be acceptable for an intermediate team of 4 python developers. We are CS majors and have to come up with a project in 3-4 months, all recommendations are welcome :)  \nPS : We want to avoid anything AI related but nothing easy too.",
    # "How to Scrape a Website that Requires a Login with Python ",
    # "How to Scrape a Website that Requires a Login with Python ",

    "Idea (or not sure if exists): automatic setdefault in dict We've all been here in our code:\n\n    d = {}\n    for key, addable in my_list:\n        if key not in d:\n            d[key] = init()\n        d[key] += addable\n\nor, for people who know [setdefault](https://docs.python.org/3/library/stdtypes.html?highlight=dict#dict.setdefault), you can save one line:\n\n        d.setdefault(key, init())\n        d[key] += addable\n\n(You save one line, but `init()` is run in every loop, which is sub-optimal if it's an expensive operation.)\n\nThere's tons of use cases. Either you're making a [Counter](https://docs.python.org/3/library/collections.html#collections.Counter), a dictionary to a `list` (or a `set`), or\n\nI'm in a point where I gotta repeat this process several times in my code, like:\n\n    d.setdefault(key1, init())\n    d[key] += addable1\n    \n    d.setdefault(key2, init())\n    d[key] += addable2\n    \n    d.setdefault(key3, init())\n    d[key] += addable3\n\nWhereas most loops would run simply as\n\n    d[key] += addable1\n    d[key] += addable2\n    d[key] += addable3\n\nWould it be possible to tell Python, if you cannot find a key, instead of throwing a `KeyError`, run an `init()` function I give you? `Counter` already does this by initializing to 0, although `Counter` only works with `int`. I'm thinking something like:\n\n    d = {}\n    d.set_universal_default(init)\n    for key, addable in my_list:\n        d[key] += addable\n\nWhat do you guys think? PEP material?",
    # "AWS lambda payload in Pythonic way. Following is my code snippet to return payload or the failure message for future error handling.However, I would like to improve the readability and maintainability.\n\n        if reportId is not None:\n            return {'payload': reportId}\n        # Future error handling\n        else:\n            return {'message': 'Fail to create report'}\n\nFollowing is the answer given by Chat GPT\n\n`return {'payload': reportId} if reportId else {'message': 'Fail to create Amazon Business &amp; Traffic report'}`\n\nCould you let me know which one is the better one, please?",
    # "Full support for slots in dataclasses Many years ago I've made a small library to provide the `__slots__` attribute to dataclasses: dataslots. It's stable, well-tested, and supports type checking. Additional features to python implementation:\n\n* Support for python 3.7 - 3.12 (python 3.10/3.11 added base support for slots).\n* Support for dynamic assignment for new variables (`__dict__` in `__slots__`).\n* Pickling frozen dataclasses (fixed in python 3.10).\n* Support for data descriptors and slots simultaneously.\n\nIf you are using older versions of python or need more from dataclasses give it a try. \n\nGithub: https://github.com/starhel/dataslots\nPyPI: https://pypi.org/project/dataslots/",
    # "Leak Detection with Sound Files Hi Folks, Please suggest a use case for 'Leak Detection' in steam trap through acoustics.. Python implementation will be helpful.. Thanks in anticipation..."
]

# reddit_test_data = [
#     "Sunday Daily Thread: What's everyone working on this week? Tell /r/python what you're working on this week! You can be bragging, grousing, sharing your passion, or explaining your pain. Talk about your current project or your pet project; whatever you want to share.",
#     "Wednesday Daily Thread: Beginner questions New to Python and have questions? Use this thread to ask anything about Python, there are no bad questions!\n\nThis thread may be fairly low volume in replies, if you don't receive a response we recommend looking at r/LearnPython or joining the Python Discord server at [https://discord.gg/python](https://discord.gg/python) where you stand a better chance of receiving a response.",
#     "What are the best Python libraries to learn for beginners? Hi everyone. I wanted to reach out and ask for some help with a Python project I'm working on. So, I'm a CS student and I recently started learning Python and so far, I’m loving it. It's a great language and I even like it better than JavaScript. Anyways, I'm looking forward to continuing to improve my skills in this area.\n\nOne thing I've been struggling with though is all the libraries that come with Python. I'm particularly interested in machine learning, but I'm down to learn any popular libraries that you guys recommend.\n\nI've been doing some research online, but I figured why not ask Reddit. So, if you guys have any good libraries to suggest, that'd be great. Also, if you know of any good places to learn these libraries, I'm all ears.\n\nSo far, I've picked out a few libraries that I found:\n\n* [NumPy](https://numpy.org/): Scientific computing library and I know this one is the most popular especially in Data Science.\n* [DocArray](https://github.com/docarray/docarray): Multimodal Data Library\n* [TensorFlow](https://www.tensorflow.org/) and [PyTorch](https://pytorch.org/): Deep learning library\n* [python-benedict](https://github.com/fabiocaccamo/python-benedict): Dictionary manipulation library\n\nI know we'll be moving on to other languages next semester, but I want to make sure I have a solid understanding of Python as well. I would really appreciate it if you guys could give me some more suggestions. If you have any personal experience with any of these libraries, I would love to hear about it.\n\nNext semester, we'll be moving on to other languages, but I want to make sure I have a solid understanding of Python too. If you have any more libraries to recommend, I'd be grateful.\n\nAlso, if you have any personal experience with any of these libraries or have any project ideas, I'd love to hear about it.\n\nThanks for anyone helping out. Looking forward to diving into these libraries and learning more.",
#     "What does Python uniquely offer for automation? I write JavaScript and when we launched our open source business automation tool, we let users write Node.js code as part of their flows if they can't find an out-of-the-box piece for it.\n\nWe keep hearing from users that they prefer to write Python over JavaScript. We'll add it eventually since it's being consistently requested.\n\nBut.. I'd like to understand from the perspective of Python developers, what is it that Python offers that other languages (namely JavaScript) don't? Any specific features or libraries that you think you'd rely on for automation jobs?\n\nI mean by automation things like: syncing data from service A to service B and so.",
#     "A Music Theory Telegram Bot written in Python This is a Telegram Bot written in Python that helps you to learn Music Theory on the go (audio and visual).\n\n[Music Theory Telegram Bot](https://preview.redd.it/gu0l3xnnsefa1.png?width=960&amp;format=png&amp;auto=webp&amp;v=enabled&amp;s=a8b3e8eda0211d08d4bbe30718b4a6eca73d8b87)\n\nThe application is using python-telegram-bot library\n\nHere you can watch a video on how this application was created: [https://www.youtube.com/watch?v=WCQai649s\\_Q](https://www.youtube.com/watch?v=WCQai649s_Q)\n\nYou can find the full source code on github: [https://github.com/2CoderOK/music-theory-bot](https://github.com/2CoderOK/music-theory-bot)\n\nPlease let me know if you find this application helpful!",
#     "A Beginner's Guide to Mastering AI and Python [First Book on Amazon]  Hey Redditors!\n\nI just wanted to share some exciting news about my latest book, Python and AI: The Ultimate Party Guide for Mastering the Magic of Code! This book is a beginner's guide to AI and Python and is designed to help you master the art of coding with ease.\n\nWith this guide, you'll learn how to incorporate AI into your projects and develop your skills in Python programming. The book covers all the essential concepts, from basic programming to complex AI algorithms, and is packed with interactive examples and hands-on exercises to help you build your knowledge.\n\nAnd the best part? It's designed to be a fun and enjoyable journey, so you'll never get bored along the way! Whether you're a seasoned coder or a complete beginner, this book will help you take your skills to the next level.\n\nIf you're looking to get into AI and Python programming, this book is the perfect starting point. So what are you waiting for? Grab your copy now and start your journey to becoming a coding master!\n\nAnd here's the real kicker: I need your help to make this book #1 on Amazon's Best New Arrival list. If you love Python and AI, and want to help other beginners like yourself, then please buy a copy and leave a positive review. Your support will go a long way in spreading the word and making this book a success.\n\nThank you in advance! Let's make Python and AI: The Ultimate Party Guide for Mastering the Magic of Code the #1 Best New Arrival on Amazon!\n\n$0.99 on [Amazon](https://www.amazon.com/Python-AI-Ultimate-Party-Mastering-ebook/dp/B0BTB4Y1F3)\n\nFREE for Kindle Unlimited",
#     "Making Automatic YouTube Videos with Python Hi everyone! Awhile back I had the idea to fully automate a YouTube channel to see how successful it could become. I'm not new to programming, but I certainly am to Python.\n\nHere's a video I made explaining the process: [https://youtu.be/ZmSb3LZDdf0](https://youtu.be/ZmSb3LZDdf0)\n\nThe way I started was to use those terrible Reddit TikTok/Reel/Shorts where people find a popular post and essentially just read it out with some funny comments. Luckily for me, people already use text-to-speech instead of their own voice, so my solution would fit right in.\n\nTo get content, I first used PRAW to access the Reddit API. I filter through that response and used pyttsv3 to generate an .mp3 of the voiceover. Then Selenium and Firefox made getting screenshots of each comment/post title really easy.\n\nThe only tricky part for me was learning how to use MoviePy to package everything up into a neatly-edited video. I explain this much better in the video above, but it basically consists of creating clip objects with each of the pictures and voiceovers, then connecting them in a CompositeVideoClip.\n\nI'm curious how many others have tried this, as I'm sure the majority of popular stolen Reddit posts can't be all made by hand.\n\nEdit for anyone who wanted source code: [https://github.com/Shifty-The-Dev/RedditVideoGenerator](https://github.com/Shifty-The-Dev/RedditVideoGenerator)",
#     "How to Iterate Over Rows in pandas, and Why You Shouldn't – Real Python ",
#     "Simulator of hypohtetical investment in the past - housing/stock Hi guys :)\n\nI am thinking of a little app, for personal app &amp; with friends or family.\n\nIt would be a simulation of past investment, for example if u investe d 1000€ in Google in 2000, how it would worth in 2020\n\nit could have some features like peak value (when bitcoin was highest for example)\n\nIt would be also good for housing, paris housing was so cheap 30 years ago, it almost double or triple since\n\ni am finishing an ongoig project so i dont start thinking too much about it, i know it could render quiet easy to use on a website - embedding a jupyter notebook\n\nlet me know if u saw something like this, have any tips or comments :) cheers, bye",
#     "Documentation assistant, chat bot that helps with libraries. Fully context aware Im still in the process, but this is the prototype. I will open source soon its just too rough. Think I should spend more time on it as I find it very useful.\n\n[Screenshot 1](https://imgur.com/a/wilpTys)\n\n[Prototype video](https://imgur.com/a/EAWngGo)\n\nBasically its a Chrome extension, that looks at the documentation page and allows users to query it with GPT model with context.\n\nIm requests to scrape data. Than process and prep it for embeddings using Longchain and the openAI's gpt3 as my LLM model. Here I use simple Javascript for frontend and flask backend.\n\nThus the huge advantage is that its context awareness is up to date and not a year or 2 ago like a typical GPT model on its own. You can also use it on private Docs/ repos. Just querying with GPT is good but there are still a lot of incorrect responses if library is frequently updated or not too popular, because it lack context.\n\nIn the end I want to create a nice standalone version which connect with different library indexes + different GPT services/ model\n\nCurrently im thinking to use something like redis queue processing new libraries and some vector DB to store data like Milvus,\n\nI would appreciate any feedback on this, If you find a tool like this useful or not. Also want to see if anyone would be willing to contribute to this project too",
#     "What's the best python projects for freelancing? \n\nI am trying to find some freelancing in python. \n\nIt's looks like is better to focus in web system than bots, automation and scraping.",
#     "Expense Tracker  Hello everyone,\n\nI built an expense tracker long time ago. I looked at the code several weeks ago and realized how bad it was. So I decided to rebuild it and make it better and more important: useful. I will continue working on it and maybe inplementing features like currency coonversion, taxes and more.\n\nI am happy for every feedback I get. For bugs or problems, feel free to create an Issue on GitHub.\n\nRepo: [https://github.com/Jolumine/exptrk](https://github.com/Jolumine/exptrk)",
#     "Transfer the ownership of Flask-Mailing Hi,\nI want to transfer the ownership of the below mentioned project.\n\nFlask-Mailing: Flask mail system for sending mails(individual, bulk) ,attachments(individual, bulk) fully asynchronously..\n\nGitHub: https://github.com/marktennyson/flask-mailing\n\nPYPI: https://pypi.org/project/Flask-Mailing/\n\nDocumentation: https://gh.aniketsarkar.info/flask-mailing/",
#     "Detailed tutorial on How to Use Python and Beautiful Soup for Web Scraping Hello everyone,\nI created a detailed article on how to do web scraping using python and beautiful soup module. This tutorial will cover uses of webscraping, how to install and setup and performing live webscraping on website and how to collect data according to needs. \n\nAs an beginner he can understand all the above mentioned details and learn basics from it and practice it\n\nArticle link [How to Use Python and Beautiful Soup for Web Scraping](https://ideasorblogs.in/learn-how-to-use-python-and-beautiful-soup-for-web-scraping-a-step-by-step-tutorial/)\n\nHope it will be useful for everyone\n\nLet me know in the comment if anything mentioned is wrong",
#     "5 Common Asyncio Errors in Python (and how to avoid them) ",
#     "Using Testing Library with Selenium in Python ",
#     "Cursor clicker program question Hello all,\n\nI want the program to do the following:\n\nuser clicks mouse -&gt; program, preferably in python, clicks too depending on the cursers current location\n\nHow would I go about this? Is there a name for this sort of program?\n\nThank you!",
#     "PyCharm has become horrible to work with over SSH interpreter, any similar experiences? I have been using PyCharm pro for a few years now. I dont remember when exactly but probably last year they reworked the way SSH interpreters are configured?\n\nFor a while now,  I constantly have problems with this stupid config. Maybe I am doing something wrong and it's me who is stupid but it is just so frustrating! It all worked nicely before with some simple settings.\n\n&amp;#x200B;\n\nNow I have problems like:\n\n\\-  confusing coupling of deployment and SSH\n\n\\- deployment not happening where it is supposed to be (see above)\n\n\\- SSH option wizard no longer supports pointing to anaconda directly and somehow changed to be not as intuitive as it used to be\n\n\\- debugging is a feaking hell. PyCharm always wants to jump to some temporary files (which dont have my breakpoints) and it takes me a day to try all kind of settings until it magically works and I have no clue what finally got me to the point...\n\nI have several projects on several servers and this is becoming a huge blocker in my work, being not able to debug properly.\n\n&amp;#x200B;\n\nPlease tell me I am not the only one? ",
#     "I made a ChatGPT clone using Python, but i added voice interaction functionality ! Check the code in description and tell me what do you think ! ",
#     "Django and Flutter. What Flet has joined together. &amp;#x200B;\n\nI hate boilerplate code. I hated it all my life. I made so many steps to remove these mental parasites far from me. And now, with Flet and Django it is possible.  \nAll you need is this package: [https://pypi.org/project/flet-django/](https://pypi.org/project/flet-django/).\n\n* Add 'flet\\_django' to INSTALLED\\_APPS in settings.py: INSTALLED\\_APPS += \\['flet\\_django'\\]\n* Create the main function in the file main\\_app.py at the root of your Django project:  \n\\`\\`\\`python  \nimport flet as ft  \nfrom flet\\_django.pages import GenericApp  \nmain = GenericApp(controls=\\[ft.Text(\"Hello World!\")\\])  \n\\`\\`\\`\n* Run function **main** from file **main\\_app.py** using the Django command:  \n\\`\\`\\`bash  \npython manage.py run\\_app  \n\\`\\`\\`\n* Enjoy your desktop/mobile/web flutter app.",
#     "Understanding Similarity Measures for Text Analysis ",
#     "Python Project Recommendations Hello, me and 3 of my friends have to present a project in python this semester. What topics would you think would be acceptable for an intermediate team of 4 python developers. We are CS majors and have to come up with a project in 3-4 months, all recommendations are welcome :)  \nPS : We want to avoid anything AI related but nothing easy too.",
#     "How to Scrape a Website that Requires a Login with Python ",
#
# ]
